# Generated by Django 2.2.5 on 2020-05-10 05:30

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200509_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
