# Generated by Django 2.2.5 on 2020-05-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200510_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ko', '한국어')], default='ko', max_length=2),
        ),
    ]
