# Generated by Django 2.2.5 on 2020-05-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200517_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
