# Generated by Django 2.2.5 on 2020-06-15 15:26

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='제목', max_length=140)),
                ('dish', models.CharField(help_text='요리명', max_length=140)),
                ('description', models.TextField(help_text='게시글 코멘트')),
                ('cuisine', models.TextField(help_text='요리법')),
                ('cooking_ingredients', models.TextField(help_text='요리 재료')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CookingUtensil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name_plural': 'CookingUtensils',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='content_photos')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='contents.Content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='content',
            name='cooking_utensils',
            field=models.ManyToManyField(blank=True, help_text='요리기구', related_name='contents', to='contents.CookingUtensil'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
