# Generated by Django 2.2.5 on 2020-05-09 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('dish', models.CharField(max_length=140)),
                ('dish_photos', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
                ('cuisine', models.TextField()),
                ('country_of_dish', django_countries.fields.CountryField(max_length=2)),
                ('cooking_ingredients', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CookingUtesil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Contents',
        ),
        migrations.AddField(
            model_name='content',
            name='cooking_utensils',
            field=models.ManyToManyField(blank=True, to='contents.CookingUtesil'),
        ),
        migrations.AddField(
            model_name='content',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
