# Generated by Django 2.2.5 on 2020-05-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20200509_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
