# Generated by Django 2.2.5 on 2020-05-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_content_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='like_count',
        ),
    ]
