# Generated by Django 2.2.5 on 2020-05-10 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_content_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='writer',
            new_name='user',
        ),
    ]
