# Generated by Django 2.2.5 on 2020-05-17 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_remove_content_country_of_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cooking_ingredients',
            field=models.TextField(help_text='요리 재료'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cooking_utensils',
            field=models.ManyToManyField(blank=True, help_text='요리기구', related_name='contents', to='contents.CookingUtensil'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cuisine',
            field=models.TextField(help_text='요리법'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(help_text='게시글 코멘트'),
        ),
        migrations.AlterField(
            model_name='content',
            name='dish',
            field=models.CharField(help_text='요리명', max_length=140),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(help_text='제목', max_length=140),
        ),
        migrations.AlterField(
            model_name='content',
            name='user',
            field=models.ForeignKey(help_text='작성자', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL),
        ),
    ]
