# Generated by Django 2.2.5 on 2020-05-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_auto_20200517_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='review',
            field=models.CharField(blank=True, help_text='댓글', max_length=200, null=True),
        ),
    ]
