# Generated by Django 2.2.5 on 2020-05-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_content_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='review',
        ),
    ]
