# Generated by Django 2.2.5 on 2020-05-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
