# Generated by Django 2.2.5 on 2020-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_content_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='photo',
            field=models.ManyToManyField(blank=True, help_text='사진', related_name='contents', to='contents.Photo'),
        ),
    ]
