# Generated by Django 2.2.5 on 2020-06-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0016_content_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='photo',
        ),
    ]
