# Generated by Django 2.2.5 on 2020-06-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_remove_content_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='photo',
            field=models.ImageField(blank=True, upload_to='content_photos'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
