# Generated by Django 2.2.5 on 2020-06-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0018_auto_20200629_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='photo',
        ),
        migrations.AddField(
            model_name='content',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='content_photos'),
        ),
    ]
