# Generated by Django 2.2.5 on 2020-06-29 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0019_auto_20200629_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='photos',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='content_photos')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='contents.Content')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
