# Generated by Django 2.2.5 on 2020-06-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0020_auto_20200629_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
    ]
