# Generated by Django 2.2.5 on 2020-06-30 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0021_remove_photo_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cooking_ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='cooking_utensils',
            field=models.ManyToManyField(blank=True, related_name='contents', to='contents.CookingUtensil'),
        ),
        migrations.AlterField(
            model_name='content',
            name='cuisine',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='dish',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='content',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL),
        ),
    ]
