# Generated by Django 2.2.5 on 2020-07-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0022_auto_20200630_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='cuisine',
            field=models.TextField(),
        ),
    ]
