# Generated by Django 2.2.5 on 2020-07-16 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0023_auto_20200702_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='like_users',
            field=models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
