# Generated by Django 2.2.5 on 2020-05-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='content',
            new_name='contents',
        ),
    ]
